language: node_js
node_js:
  - "0.12"
  - "4"
  - "6"
  - "8"
  - "9"

dist: trusty

before_install:
  - UPLOAD_BUILD=false
  - if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then UPLOAD_BUILD=true; fi;

install: npm install && npm run rebuild

script:
  - if [[ "$TRAVIS_NODE_VERSION" != "0.12" ]]; then npm run lint; fi
  - npm run unit && npm run integration

after_success:
  - if [[ "$UPLOAD_BUILD" == "true" ]]; then npm run upload; fi
